# Generated by Django 3.1.8 on 2021-04-18 17:32

from django.db import migrations, models
import peer_lending.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', peer_lending.users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text='Email address of the client.', max_length=125, unique=True, verbose_name='Email Address'),
        ),
    ]
